language: node_js
node_js:
  - 10.16
env:
deploy:
  skip_cleanup: true
install:
  - git pull
  - npm ci
before_script:
  - npm install -g pm2
  - cd $TRAVIS_BUILD_DIR && pm2 start ecosystem.config.js
script:
  - npm test --coverage
