language: node_js
node_js:
  - 10.16
env:
  - NODE_ENV=production
branches:
  only:
  - master
install:
  - npm ci
before_script:
  - npm install -g pm2
script:
  - cd ../config
  - pm2 start ecosystem.config.js
