language: node_js
node_js:
  - 10.16
env:
  - NODE_ENV=production
branches:
  only:
  - master
install:
  - npm ci
before_script:
  - cat $(pwd)
  - npm install -g pm2
  - cd $(pwd)/../config/
script:
  - pm2 start ecosystem.config.js
