language: node_js
node_js:
  - 10.16
env:
deploy:
- provider: script
  skip_cleanup: true
  script: "cd $TRAVIS_BUILD_DIR && git pull"
  # on:
  #   branch: master
after_deploy:
  - npm install -g pm2
  - cd $TRAVIS_BUILD_DIR && pm2 start ecosystem.config.js
