language: node_js
node_js:
  - 10.16
env:
  - NODE_ENV=production
  - APP_URL=http://www.xn--80aaf8admgsd3i.xn--p1acf
  - CLIENT_URL=http://www.xn--80aaf8admgsd3i.xn--p1acf
  - APP_PORT=3050
  - MONGO_URI=mongodb://127.0.0.1:27017/slavsalon
  - CYPHER_SECRET=slavs
  - SECRET_JWT_TOKEN=slavsalon
branches:
  only:
  - master
install:
  - npm ci
before_script:
  - npm install -g pm2
script:
  - pm2 start ecosystem.config.js
